import { Link } from "@tanstack/react-router";
import { ArrowRight, Building2 } from "lucide-react";
import { Bar, BarChart, CartesianGrid, Cell, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Button } from "@/components/ui/button";
import { checkpoints } from "@/lib/pramaan-data";
import { usePramaan } from "./app-context";
import { CaseTable, MetricCard, PageHeader, Panel, StatusBadge } from "./ui";

const riskData = [{ name: "Low Risk", value: 113, fill: "var(--success)" }, { name: "Medium Risk", value: 10, fill: "var(--warning)" }, { name: "High Risk", value: 4, fill: "var(--destructive)" }];

export function DashboardPage() {
  const { cases } = usePramaan();
  return <><PageHeader title="Identity Trust Command Center" subtitle="Checkpoint verification overview" actions={<Button asChild><Link to="/high-risk">Review high-risk cases<ArrowRight /></Link></Button>} /><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><MetricCard label="Verifications today" value="127" note="Across active checkpoints" /><MetricCard label="Cleared" value="113" tone="success" note="89% of screenings" /><MetricCard label="Review required" value="10" tone="warning" note="Awaiting supervisor" /><MetricCard label="High risk" value="4" tone="danger" note="Immediate attention" /><MetricCard label="Average screening time" value="18 sec" note="Within target" /></div><div className="mt-6 grid gap-6 xl:grid-cols-[1.65fr_1fr]"><Panel title="Live verification activity" description="Most recent screening outcomes" action={<Button asChild variant="ghost" size="sm"><Link to="/verifications">Full queue<ArrowRight /></Link></Button>}><CaseTable cases={cases.slice(0, 3)} compact /></Panel><Panel title="Risk distribution" description="Today's 127 completed screenings"><div className="h-56"><ResponsiveContainer width="100%" height="100%"><BarChart data={riskData} layout="vertical" margin={{ left: 8, right: 12 }}><CartesianGrid strokeDasharray="3 3" horizontal={false} stroke="var(--border)" /><XAxis type="number" hide /><YAxis type="category" dataKey="name" width={86} tick={{ fontSize: 11, fill: "var(--muted-foreground)" }} axisLine={false} tickLine={false} /><Tooltip cursor={{ fill: "var(--muted)" }} /><Bar dataKey="value" radius={[0, 3, 3, 0]}>{riskData.map((item) => <Cell key={item.name} fill={item.fill} />)}</Bar></BarChart></ResponsiveContainer></div></Panel></div><div className="mt-6"><Panel title="Checkpoint activity" description="Operational view across demonstration locations"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">{checkpoints.map((item) => <Link key={item.id} to="/analytics" className="group border border-border p-4 transition-colors hover:border-primary"><div className="flex items-start justify-between"><Building2 className="size-5 text-primary" /><StatusBadge status={item.status} /></div><h3 className="mt-4 font-semibold">{item.name}</h3><div className="mt-3 grid grid-cols-3 gap-2 text-xs"><div><span className="block text-muted-foreground">Checks</span><b className="text-base">{item.verifications}</b></div><div><span className="block text-muted-foreground">Avg.</span><b className="text-base">{item.averageTime}</b></div><div><span className="block text-muted-foreground">High risk</span><b className="text-base text-destructive">{item.highRisk}</b></div></div></Link>)}</div></Panel></div></>;
}