import { Link } from "@tanstack/react-router";
import { useMemo, useState } from "react";
import { ArrowRight, CalendarDays, CheckCircle2, Clock3, FileSearch, Fingerprint, Search, SlidersHorizontal } from "lucide-react";
import { Bar, BarChart, CartesianGrid, Cell, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Switch } from "@/components/ui/switch";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { anomalyData, checkpoints, volumeData } from "@/lib/pramaan-data";
import type { AuditEvent, CaseStatus } from "@/lib/pramaan-types";
import { usePramaan } from "./app-context";
import { CaseTable, DecisionSupportNote, MetricCard, PageHeader, Panel, RiskPill, StatusBadge } from "./ui";

export function VerificationsPage({ highRiskOnly = false }: { highRiskOnly?: boolean }) {
  const { cases } = usePramaan();
  const [tab, setTab] = useState(highRiskOnly ? "High Risk" : "All");
  const [checkpoint, setCheckpoint] = useState("All");
  const [documentType, setDocumentType] = useState("All");
  const filtered = cases.filter((item) => (tab === "All" || item.status === tab) && (checkpoint === "All" || item.checkpoint === checkpoint) && (documentType === "All" || item.document.type === documentType));
  return <><PageHeader title={highRiskOnly ? "High-Risk Cases" : "Verification Queue"} subtitle={highRiskOnly ? "Priority cases requiring authorized investigation" : "Review and manage checkpoint screening outcomes"} /><Panel><div className="flex flex-col gap-4"><Tabs value={tab} onValueChange={setTab}><TabsList className="h-auto flex-wrap justify-start">{(highRiskOnly ? ["High Risk", "Review"] : ["All", "Cleared", "Review", "High Risk"]).map((value) => <TabsTrigger key={value} value={value}>{value}</TabsTrigger>)}</TabsList></Tabs><div className="grid gap-3 border-y bg-muted/30 py-3 sm:grid-cols-2 lg:grid-cols-4"><div className="relative"><CalendarDays className="absolute left-3 top-2.5 size-4 text-muted-foreground" /><Input type="date" aria-label="Date filter" className="pl-9" /></div><Select value={checkpoint} onValueChange={setCheckpoint}><SelectTrigger><SelectValue placeholder="Checkpoint" /></SelectTrigger><SelectContent><SelectItem value="All">All checkpoints</SelectItem><SelectItem value="IGI Demo">IGI Demo</SelectItem><SelectItem value="Delhi Demo">Delhi Demo</SelectItem></SelectContent></Select><Select value={documentType} onValueChange={setDocumentType}><SelectTrigger><SelectValue placeholder="Document type" /></SelectTrigger><SelectContent><SelectItem value="All">All documents</SelectItem><SelectItem value="Passport">Passport</SelectItem><SelectItem value="Visa">Visa</SelectItem></SelectContent></Select><div className="flex items-center gap-2 px-2 text-sm text-muted-foreground"><SlidersHorizontal className="size-4" />{filtered.length} mock records shown</div></div><CaseTable cases={filtered} /></div></Panel></>;
}

export function IdentityIntelligencePage() {
  const { cases } = usePramaan();
  const [selectedId, setSelectedId] = useState(cases.at(0)?.identity.id ?? "");
  const selected = cases.find((item) => item.identity.id === selectedId) ?? cases.at(0);
  if (!selected) return <div className="p-6 text-sm text-muted-foreground">No identity records are available.</div>;
  return <><PageHeader title="Identity Intelligence" subtitle="Verification evidence and historical document observations" /><div className="mb-5 flex max-w-xl gap-2"><div className="relative flex-1"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground" /><Input className="pl-9" placeholder="Search identity or document number" /></div><Select value={selectedId} onValueChange={setSelectedId}><SelectTrigger className="w-48"><SelectValue /></SelectTrigger><SelectContent>{cases.slice(0, 2).map((item) => <SelectItem key={item.identity.id} value={item.identity.id}>{item.identity.name}</SelectItem>)}</SelectContent></Select></div><div className="grid gap-6 xl:grid-cols-[1.4fr_1fr]"><Panel title="Verification history" description={`Identity record ${selected.identity.id}`}><div className="mb-5 flex items-center gap-4 border-b pb-5"><div className="grid size-14 place-items-center rounded-full bg-secondary text-lg font-bold text-primary">{selected.identity.initials}</div><div><h2 className="font-display text-xl font-bold">{selected.identity.name}</h2><p className="text-xs text-muted-foreground">Document {selected.document.number} · Mock evidence record</p></div></div><div className="relative space-y-0 before:absolute before:bottom-5 before:left-[15px] before:top-5 before:w-px before:bg-border">{selected.identity.history.map((event, index) => <div key={`${event.date}-${index}`} className="relative grid grid-cols-[32px_70px_1fr_auto] items-center gap-3 py-3"><span className="relative z-10 grid size-8 place-items-center rounded-full border bg-card"><Clock3 className="size-3 text-primary" /></span><span className="text-xs font-semibold">{event.date}</span><div><div className="text-sm font-medium">{event.checkpoint}</div><div className="text-xs text-muted-foreground">{event.document} verification</div></div><StatusBadge status={event.status} /></div>)}</div></Panel><Panel title="Observed patterns" description="Evidence patterns only — not criminal profiling"><div className="space-y-3">{selected.identity.patterns.map((pattern) => <div key={pattern} className="flex items-center gap-3 border p-3 text-sm"><Fingerprint className="size-4 text-primary" />{pattern}</div>)}</div><div className="mt-5"><DecisionSupportNote /></div><Button asChild variant="outline" className="mt-4 w-full"><Link to="/cases/$caseId" params={{ caseId: selected.id }}>Open latest verification<ArrowRight /></Link></Button></Panel></div></>;
}

const riskPie = [{ name: "Low", value: 89, fill: "var(--success)" }, { name: "Medium", value: 8, fill: "var(--warning)" }, { name: "High", value: 3, fill: "var(--destructive)" }];

export function AnalyticsPage() {
  const [period, setPeriod] = useState("Today");
  const multiplier = period === "Today" ? 1 : period === "7 days" ? 5.4 : 19.8;
  const scaledVolume = useMemo(() => volumeData.map((item) => ({ ...item, verifications: Math.round(item.verifications * multiplier) })), [multiplier]);
  return <><PageHeader title="Operational Analytics" subtitle="Verification volume, risk, and anomaly trends" actions={<Tabs value={period} onValueChange={setPeriod}><TabsList><TabsTrigger value="Today">Today</TabsTrigger><TabsTrigger value="7 days">7 days</TabsTrigger><TabsTrigger value="30 days">30 days</TabsTrigger></TabsList></Tabs>} /><div className="grid gap-3 sm:grid-cols-3"><MetricCard label="Total screenings" value={Math.round(127 * multiplier)} note={period} /><MetricCard label="High-risk rate" value="3.1%" tone="danger" note="Across all checkpoints" /><MetricCard label="Average time" value="19 sec" note="Target below 25 sec" /></div><div className="mt-6 grid gap-6 xl:grid-cols-2"><Panel title="Verification volume over time"><div className="h-64"><ResponsiveContainer width="100%" height="100%"><LineChart data={scaledVolume}><CartesianGrid stroke="var(--border)" strokeDasharray="3 3" /><XAxis dataKey="name" tick={{ fontSize: 11 }} /><YAxis tick={{ fontSize: 11 }} /><Tooltip /><Line type="monotone" dataKey="verifications" stroke="var(--primary)" strokeWidth={3} dot={{ fill: "var(--primary)" }} /></LineChart></ResponsiveContainer></div></Panel><Panel title="Risk distribution"><div className="h-64"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={riskPie} dataKey="value" innerRadius={55} outerRadius={90} paddingAngle={3}>{riskPie.map((entry) => <Cell key={entry.name} fill={entry.fill} />)}</Pie><Tooltip /></PieChart></ResponsiveContainer></div><div className="flex justify-center gap-5 text-xs">{riskPie.map((entry) => <span key={entry.name} className="flex items-center gap-2"><i className="size-2 rounded-full" style={{ background: entry.fill }} />{entry.name} {entry.value}%</span>)}</div></Panel><Panel title="High-risk cases by checkpoint"><div className="h-64"><ResponsiveContainer width="100%" height="100%"><BarChart data={checkpoints}><CartesianGrid stroke="var(--border)" strokeDasharray="3 3" /><XAxis dataKey="name" tick={{ fontSize: 10 }} interval={0} /><YAxis allowDecimals={false} /><Tooltip /><Bar dataKey="highRisk" fill="var(--destructive)" radius={[3, 3, 0, 0]} /></BarChart></ResponsiveContainer></div></Panel><Panel title="Common anomaly categories"><div className="space-y-4">{anomalyData.map((item) => <div key={item.name}><div className="mb-1 flex justify-between text-xs"><span>{item.name}</span><b>{item.value}</b></div><div className="h-2 bg-muted"><div className="h-full bg-primary" style={{ width: `${item.value * 4}%` }} /></div></div>)}</div></Panel></div></>;
}

export function AuditTrailPage() {
  const { auditEvents } = usePramaan();
  const [selected, setSelected] = useState<AuditEvent | null>(null);
  return <><PageHeader title="Secure Audit Trail" subtitle="Traceable verification and investigator actions" /><Panel><Table><TableHeader><TableRow><TableHead>Timestamp</TableHead><TableHead>Case ID</TableHead><TableHead>Officer</TableHead><TableHead>Action</TableHead><TableHead>Checkpoint</TableHead><TableHead>Status</TableHead><TableHead className="text-right">Details</TableHead></TableRow></TableHeader><TableBody>{auditEvents.map((event) => <TableRow key={event.id}><TableCell className="font-mono">{event.timestamp}</TableCell><TableCell className="font-mono text-xs font-semibold">{event.caseId}</TableCell><TableCell>{event.officer}</TableCell><TableCell>{event.action}</TableCell><TableCell>{event.checkpoint}</TableCell><TableCell><StatusBadge status={event.status} /></TableCell><TableCell className="text-right"><Button variant="ghost" size="icon" onClick={() => setSelected(event)} aria-label={`View ${event.id}`}><FileSearch /></Button></TableCell></TableRow>)}</TableBody></Table><div className="mt-4 border border-info/25 bg-info-soft p-3 text-xs text-info">Prototype audit records are simulated. Production deployment would use secure, access-controlled storage.</div></Panel><Dialog open={Boolean(selected)} onOpenChange={(open) => !open && setSelected(null)}><DialogContent><DialogHeader><DialogTitle>Audit event {selected?.id}</DialogTitle><DialogDescription>{selected?.detail}</DialogDescription></DialogHeader><div className="grid grid-cols-2 gap-4 border-t pt-4 text-sm"><div><span className="block text-xs text-muted-foreground">Officer</span>{selected?.officer}</div><div><span className="block text-xs text-muted-foreground">Checkpoint</span>{selected?.checkpoint}</div></div></DialogContent></Dialog></>;
}

export function SettingsPage() {
  const [faceThreshold, setFaceThreshold] = useState("85");
  const [alerts, setAlerts] = useState(true);
  const [saved, setSaved] = useState(false);
  return <><PageHeader title="Verification Settings" subtitle="Demonstration thresholds and display controls" /><div className="grid gap-6 xl:grid-cols-2"><Panel title="Screening thresholds" description="Prototype settings do not affect real systems"><label className="text-xs font-bold uppercase text-muted-foreground" htmlFor="face-threshold">Face match review threshold</label><div className="mt-2 flex items-center gap-3"><Input id="face-threshold" type="number" value={faceThreshold} onChange={(event) => setFaceThreshold(event.target.value)} /><span className="font-bold">%</span></div><div className="mt-5 flex items-center justify-between border-y py-4"><div><div className="text-sm font-semibold">High-risk alerts</div><div className="text-xs text-muted-foreground">Highlight priority cases in the queue</div></div><Switch checked={alerts} onCheckedChange={setAlerts} /></div><Button className="mt-5" onClick={() => { setSaved(true); window.setTimeout(() => setSaved(false), 2500); }}>{saved ? <><CheckCircle2 />Settings saved</> : "Save prototype settings"}</Button></Panel><Panel title="Active checkpoints" description="Displayed in the command center">{checkpoints.map((item) => <div key={item.id} className="flex items-center justify-between border-b py-3 last:border-0"><div><div className="text-sm font-semibold">{item.name}</div><div className="text-xs text-muted-foreground">{item.verifications} verifications today</div></div><Switch defaultChecked={item.status === "Operational"} /></div>)}</Panel></div></>;
}