/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AuditTrailRouteImport } from './routes/audit-trail'
import { Route as HighRiskRouteImport } from './routes/high-risk'
import { Route as IdentityIntelligenceRouteImport } from './routes/identity-intelligence'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as VerificationsRouteImport } from './routes/verifications'
import { Route as CasesCaseIdRouteImport } from './routes/cases.$caseId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditTrailRoute = AuditTrailRouteImport.update({
  id: '/audit-trail',
  path: '/audit-trail',
  getParentRoute: () => rootRouteImport,
} as any)
const HighRiskRoute = HighRiskRouteImport.update({
  id: '/high-risk',
  path: '/high-risk',
  getParentRoute: () => rootRouteImport,
} as any)
const IdentityIntelligenceRoute = IdentityIntelligenceRouteImport.update({
  id: '/identity-intelligence',
  path: '/identity-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificationsRoute = VerificationsRouteImport.update({
  id: '/verifications',
  path: '/verifications',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesCaseIdRoute = CasesCaseIdRouteImport.update({
  id: '/cases/$caseId',
  path: '/cases/$caseId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/audit-trail': typeof AuditTrailRoute
  '/high-risk': typeof HighRiskRoute
  '/identity-intelligence': typeof IdentityIntelligenceRoute
  '/settings': typeof SettingsRoute
  '/verifications': typeof VerificationsRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/audit-trail': typeof AuditTrailRoute
  '/high-risk': typeof HighRiskRoute
  '/identity-intelligence': typeof IdentityIntelligenceRoute
  '/settings': typeof SettingsRoute
  '/verifications': typeof VerificationsRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/audit-trail': typeof AuditTrailRoute
  '/high-risk': typeof HighRiskRoute
  '/identity-intelligence': typeof IdentityIntelligenceRoute
  '/settings': typeof SettingsRoute
  '/verifications': typeof VerificationsRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/audit-trail'
    | '/high-risk'
    | '/identity-intelligence'
    | '/settings'
    | '/verifications'
    | '/cases/$caseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/audit-trail'
    | '/high-risk'
    | '/identity-intelligence'
    | '/settings'
    | '/verifications'
    | '/cases/$caseId'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/audit-trail'
    | '/high-risk'
    | '/identity-intelligence'
    | '/settings'
    | '/verifications'
    | '/cases/$caseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AuditTrailRoute: typeof AuditTrailRoute
  HighRiskRoute: typeof HighRiskRoute
  IdentityIntelligenceRoute: typeof IdentityIntelligenceRoute
  SettingsRoute: typeof SettingsRoute
  VerificationsRoute: typeof VerificationsRoute
  CasesCaseIdRoute: typeof CasesCaseIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-trail': {
      id: '/audit-trail'
      path: '/audit-trail'
      fullPath: '/audit-trail'
      preLoaderRoute: typeof AuditTrailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/high-risk': {
      id: '/high-risk'
      path: '/high-risk'
      fullPath: '/high-risk'
      preLoaderRoute: typeof HighRiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/identity-intelligence': {
      id: '/identity-intelligence'
      path: '/identity-intelligence'
      fullPath: '/identity-intelligence'
      preLoaderRoute: typeof IdentityIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verifications': {
      id: '/verifications'
      path: '/verifications'
      fullPath: '/verifications'
      preLoaderRoute: typeof VerificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/$caseId': {
      id: '/cases/$caseId'
      path: '/cases/$caseId'
      fullPath: '/cases/$caseId'
      preLoaderRoute: typeof CasesCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  AuditTrailRoute: AuditTrailRoute,
  HighRiskRoute: HighRiskRoute,
  IdentityIntelligenceRoute: IdentityIntelligenceRoute,
  SettingsRoute: SettingsRoute,
  VerificationsRoute: VerificationsRoute,
  CasesCaseIdRoute: CasesCaseIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
